spring:
  application:
    name: master-router
db:
  url: r2dbc:mariadb://${db.user}:${db.password}@${db.host}:3306/${db.schema}?${db.option}
  user: ""
  password: ""
  host: ""
  schema: ""
  option: ""
