spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${management.address}
    password: ENC(eLJ/Us1GUOiQ1iRAhY4W5PouHz2RfDaiC4ctdbZx4ho=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
db:
  url: r2dbc:mariadb://${db.user}:${db.password}@${db.host}:${db.port}/${db.schema}?${db.option}
  user: ENC(sJwAPDpFpCpYliO8CL7vTA==)
  password: ENC(KE4rra8HZD1EcALaImpUG5IA2JzKyYm8)
  host: ENC(P+srQ8WFc36tTDGtn8g7MVfT4ro4f2CxQB7mLt1vzk8=)
  port: ENC(e92pgEpnwJuZNdWXX4cc1g==)
  schema: ENC(dA27LvTvk/SYxnOspgce/Sh9KVqG1Hvr)
  option: ""
management:
  address: ENC(PhaQ3ZLpQWvWcDJxFv5T8c43cYlhcrSqIo715MIi2f0=)